ALTER TABLE news
  ADD COLUMN IF NOT EXISTS image_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS image_size INTEGER,
  ADD COLUMN IF NOT EXISTS additional_image_meta JSONB DEFAULT '[]';

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS image_file_name TEXT,
  ADD COLUMN IF NOT EXISTS image_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS image_size INTEGER;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS file_name TEXT,
  ADD COLUMN IF NOT EXISTS file_type TEXT,
  ADD COLUMN IF NOT EXISTS file_size INTEGER;
